	// INICIO DA RAM SCREEN 16384
	// FINAL DA RAM SCREEN 24575

	@SCREEN
	D=M  //PEGA O PRIMEIRO ENDEREÇO DA MEMORIA SCREEN
	@16
	M=D  //ALOCA O ENDEREÇO 1 NA RAM 16
	@1
	D=M   //PEGA O ÚLTIMO ENDEREÇO DA MEMORIA SCREEN
	@17
	M=D   // ALOCA O ÚLTIMO ENDEREÇO DA RAM SCREEN NA RAM 17
(LOOPCOMECO)	
	@KBD
	D=M       
	@LOOPTELABRANCA
	D;JEQ
	@LOOPTELAPRETA
	D;JGT
(LOOPTELAPRETA)        //INICIA O LOOP PARA TROCAR O VALOR DA RAM SCREEN  PARA -1   
	@16
	A=M   // PEGA O VALOR DE M E JOGA EM A
	M=-1  // MODIFICA O VALOR DA POSIÇAO RAM[M] PARA -1 
	@16
	M=M+1 //INCREMENTA O VALOR DA RAM EM +1
	D=M
	@17
	D=M-D //COMPARA O VALOR DA RAM SCREEN ATUAL COM O VALOR DA RAM SCREEN FINAL
	@LOOPTELAPRETA
	D;JGE
	@LOOPCOMECO
	0;JMP
(LOOPTELABRANCA)        //INICIA O LOOP PARA TROCAR O VALOR DA RAM SCREEN  PARA -1   
	@16
	A=M   // PEGA O VALOR DE M E JOGA EM A
	M=0  // MODIFICA O VALOR DA POSIÇAO RAM[M] PARA 0 
	@16
	M=M+1 //INCREMENTA O VALOR DA RAM EM +1
	D=M
	@17
	D=M-D //COMPARA O VALOR DA RAM SCREEN ATUAL COM O VALOR DA RAM SCREEN FINAL
	@LOOPTELABRANCA
	D;JGE
	@LOOPCOMECO
	0;JMP
	
	
	@LOOPCOMECO
	@SCREEN
	D=M
	@16
	M=D
	0;JMP      //LOOP DE FINAL
	
